=== LVamos/Chipotle/Chipotle/Map.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="terrainType">
    <xs:restriction base="xs:string" >
      <xs:enumeration value="Grass" />
      <xs:enumeration value="Linoleum" />
      <xs:enumeration value="Carpet" />
      <xs:enumeration value="Gravel" />
      <xs:enumeration value="Asfalt" />
      <xs:enumeration value="Cobblestones" />
      <xs:enumeration value="Tiles" />
      <xs:enumeration value="Wood" />
      <xs:enumeration value="Mud" />
      <xs:enumeration value="Puddle" />
      <xs:enumeration value="Concrete" />
      <xs:enumeration value="Clay" />
      <xs:enumeration value="Wall" />
      <xs:enumeration value="Bush" />
    </xs:restriction>
  </xs:simpleType>
  
  
  <xs:simpleType name="localityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Indoor" />
      <xs:enumeration value="Outdoor" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fourCoordinates">
    <xs:restriction base="xs:token">
      <xs:pattern value="\d+, +\d+, +\d+, +\d+" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="twoCoordinates">
    <xs:restriction base="xs:token">
      <xs:pattern value="\d+, +\d+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="perimeterWalls">
    <xs:restriction base="xs:string">
      <xs:enumeration value="All" />
      <xs:enumeration value="None" />
      <xs:enumeration value="Left" />
      <xs:enumeration value="Front" />
      <xs:enumeration value="Right" />
      <xs:enumeration value="Back" />
      <xs:enumeration value="Left, Front" />
      <xs:enumeration value="Left, Right" />
      <xs:enumeration value="Left, Back" />
      <xs:enumeration value="Left, Front, Right" />
      <xs:enumeration value="Left, Front, Back" />
      <xs:enumeration value="Front, Right" />
      <xs:enumeration value="Front, Right, Back" />
      <xs:enumeration value="Right, Back" />
      <xs:enumeration value="Front, Back" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="map" >
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="passages" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              
              <xs:element name="passage" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="indexedname" type="xs:string" use="required" />
                  <xs:attribute name="from" type="xs:string" use="required" />
                  <xs:attribute name="to" type="xs:string" use="required" />
                  <xs:attribute name="door" type="xs:boolean" default="true"  />
                  <xs:attribute name="closed" type="xs:boolean" default="true"  />
                  <xs:attribute name="coordinates" type="fourCoordinates" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="localities" minOccurs="1"   maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              
              <xs:element name="locality" maxOccurs="unbounded" >
                <xs:complexType>

                  <xs:sequence>
                    <xs:sequence>

                      <xs:element name="panel" minOccurs="0"  maxOccurs="unbounded" >
                        <xs:complexType>

                          <xs:attribute name="coordinates" type="fourCoordinates" use="required" />
                          <xs:attribute name="terrain" type="terrainType" default="Grass"  />
                          <xs:attribute name="canBeOccupied" type="xs:boolean" default="true"  />

                        </xs:complexType>
                      </xs:element>

                    </xs:sequence>

                    <xs:sequence>

                      <xs:element name="object" minOccurs="0"  maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:attribute name="indexedname" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="friendlyname" type="xs:string" use="required" />
                        <xs:attribute name="coordinates" type="fourCoordinates" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  </xs:sequence>

                  <xs:attribute name="indexedname" type="xs:string" use="required" />
                  <xs:attribute name="friendlyname" type="xs:string" use="required" />
                  <xs:attribute name="type" type="localityType" default="Outdoor"  />
                  <xs:attribute name="coordinates" type="fourCoordinates" use="required" />
                  <xs:attribute name="height" type="xs:unsignedByte" default="0"  />
                  <xs:attribute name="defaultTerrain" type="terrainType" default="Concrete"  />
                  <xs:attribute name="walls" type="perimeterWalls" default="None"  />

                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LVamos/Chipotle/Chipotle/Vzor mapy - kopie(novější záloha).xml
<?xml version="1.0" encoding="utf-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Map.xsd">
  <passages>
    <passage from="příjezdová cesta" to="u bazénu" door="false" closed="false" coordinates="1001, 1040, 1010, 1040" />
    <passage from="u bazénu" to="hala" door="true" closed="true" coordinates="1039, 1052, 1039, 1048" />
  </passages>
  <localities>
    <!--Příjezdová cesta-->
    <locality name="příjezdová cesta" coordinates="1000, 1040, 1040, 1000" type="Outdoor" defaultTerrain="Asfalt" walls="None" height="0">
      <!--Dlážděná cesta vepředu vlevo-->
      <panel terrain="Tiles" coordinates="0, 0, 24, 4" canBeOccupied="true" />
      <!--Křoví úplně nahoře-->
      <panel terrain="Bush" coordinates="11, 0, 39, 0" canBeOccupied="false" />
      <!--štěrk vlevo-->
      <panel terrain="Gravel" coordinates="0, 5, 24, 40" canBeOccupied="true" />
      <!--štěrk vpravo-->
      <panel terrain="Gravel" coordinates="35, 1, 40, 40" canBeOccupied="true" />
      <!--Dřevěný plot vlevo nahoře-->
      <object name="plot" coordinates="0, 0, 0, 5" />
      <!--Columbovo auto u brány-->
      <object name="auto" coordinates="25, 30, 27, 34" />
      <!--Elektrická brána úplně vzadu-->
      <object name="brána" coordinates="23, 40, 39, 40" />
      <!--Dřevěný plot vepředu-->
      <object name="plot" coordinates="0, 6, 21, 6" />
      <!--Dřevěný plot vlevo-->
      <object name="plot" coordinates="22, 6, 22, 40" />
      <!--Dřevěný plot vpravo-->
      <object name="plot" coordinates="40, 0, 40, 40" />
    </locality>
    <!--Bazén-->
    <locality name="u bazénu" coordinates="900, 1100, 1039, 1041" type="Outdoor" height="0" walls="Left, Front, Right" defaultTerrain="Tiles">
      <!--Díra na dveře vpravo dole-->
      <panel terrain="Tiles" coordinates="139, 48, 139, 52" canBeOccupied="true" />
      <!--hlína po celém levém okraji-->
      <panel terrain="Clay" coordinates="1, 1, 20, 58" canBeOccupied="true" />
      <!--hlína po celé horní straně-->
      <panel terrain="Clay" coordinates="21, 1, 138, 9" canBeOccupied="true" />
      <!--tráva po většině horní strany-->
      <panel terrain="Grass" coordinates="23, 2, 131, 7" canBeOccupied="true" />
      <!--křoví vlevo nahoře-->
      <panel terrain="Bush" coordinates="30, 1, 42, 2" canBeOccupied="true" />
      <!--křoví vlevo nahoře-->
      <panel terrain="Bush" coordinates="18, 1, 25, 2" canBeOccupied="true" />
      <!--křoví vlevo nahoře-->
      <panel terrain="Bush" coordinates="8, 1, 13, 2" canBeOccupied="true" />
      <!--křoví vlevo nahoře-->
      <panel terrain="Bush" coordinates="2, 1, 4, 2" canBeOccupied="true" />
      <!--trávník vlevo nahoře-->
      <panel terrain="Grass" coordinates="3, 4, 18, 12" canBeOccupied="true" />
      <!--trávník vlevo dole-->
      <panel terrain="Grass" coordinates="2, 30, 18, 57" canBeOccupied="true" />
      <!--louže nalevo od bazénu-->
      <panel terrain="Puddle" coordinates="31, 34, 33, 40" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="34, 33, 38, 38" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="36, 31, 39, 32" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="35, 32, 35, 32" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="37, 30, 39, 30" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="37, 30, 39, 30" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="38, 29, 39, 29" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="39, 28, 39, 28" canBeOccupied="true" />
      <!--betonový plácek mezi lavičkami-->
      <panel terrain="Concrete" coordinates="12, 32, 18, 38" canBeOccupied="true" />
      <!--stromy u levé zdi-->
      <object name="strom" coordinates="4, 5, 4, 5" />
      <object name="strom" coordinates="2, 34, 2, 34" />
      <object name="strom" coordinates="2, 44, 2, 44" />
      <object name="strom" coordinates="2, 57, 2, 57" />
      <object name="mrtvola" coordinates="36, 39, 36, 40" />
      <!--záhon růží vlevo nad lavičkami-->
      <object name="růže" coordinates="2, 18, 12, 24" />
      <!--gril mezi lavičkami-->
      <object name="gril" coordinates="13, 35, 15, 35" />
      <!--lavička u levé zdi-->
      <object name="lavička" coordinates="12, 39, 17, 40" />
      <!--lavička u levé zdi-->
      <object name="lavička" coordinates="12, 30, 15, 31" />
      <!--lavička u levé zdi-->
      <object name="lavička" coordinates="10, 31, 11, 40" />
      <!--hadice u levé zdi-->
      <object name="hadice" coordinates="1, 37, 1, 39" />
      <!--Telefon u bazénu-->
      <object name="telefon" coordinates="81, 30, 81, 30" />
      <!--popelnice vlevém dolním rohu-->
      <object name="popelnice" coordinates="12, 58, 12, 58" />
      <!--Odrazové prkno na kraji bazénu-->
      <object name="prkno" coordinates="39, 36, 39, 36" />
      <!--Schůdky na rohu bazénu-->
      <object name="schůdky" coordinates="39, 38, 39, 39" />
      <!--Bazén uprostřed-->
      <object name="bazén" coordinates="40, 20, 80, 40" />
      <!--Dřevěný plot na dolní straně-->
      <object name="plot" coordinates="1, 59, 100, 59" />
    </locality>
    <!--hala ve wagnerově domě-->
    <locality name="hala" type="Indoor" defaultTerrain="Carpet" height="4" walls="Front, Right, Back" coordinates="1040, 1059, 1061, 1041">
      <!--okno napravo-->
      <object name="okno" coordinates="15, 18, 20, 18" />
      <!--vitrýna s poháry napravo u zdi-->
      <object name="vitrýna" coordinates="3, 17, 10, 17" />
      <!--falešné dveře napravo od stolu-->
      <object name="dveře" coordinates="6, 0, 6, 0" />
      <!--rádio nalevo od stolu-->
      <object name="rádio" coordinates="0, 1, 0, 1" />
      <!--pracovní stůl-->
      <object name="stůl" coordinates="1, 1, 2, 2" />
      <!--kancelářská židle-->
      <object name="židle" coordinates="1, 3, 1, 3" />
      <!--telefon-->
      <object name="telefon" coordinates="3, 1, 3, 1" />
      <!--Barový pult uprostřed-->
      <object name="barový pult" coordinates="10, 3, 10, 12" />
      <!--Barová stolička uprostřed před barem-->
      <object name="barová stolička" coordinates="9, 4, 9, 4" />
      <!--Barová stolička uprostřed před barem-->
      <object name="barová stolička" coordinates="9, 6, 9, 6" />
      <!--Barová stolička uprostřed před barem-->
      <object name="barová stolička" coordinates="9, 8, 9, 8" />
      <!--Barová stolička uprostřed před barem-->
      <object name="barová stolička" coordinates="9, 10, 9, 10" />
      <!--Barová stolička uprostřed před barem-->
      <object name="barová stolička" coordinates="9, 12, 9, 12" />
      <!--Ohromná lednice s minibarem u zadní stěny-->
      <object name="lednice s minibarem" coordinates="15, 2, 16, 5" />
      <!--kávovar vzadu velde lednice-->
      <object name="kávovar" coordinates="15, 6, 15, 6" />
      <!--dřes vzadu vedle kávovaru-->
      <object name="dřes" coordinates="16, 7, 16, 7" />
      <!--Polička s nádobím vzadu vedle dřezu-->
      <object name="polička s nádobím" coordinates="16, 12, 16, 8" />
    </locality>
  </localities>
</map>

=== LVamos/Chipotle/Chipotle/Terrain/Map.xml
<?xml version="1.0" encoding="utf-8"?>
<map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Map.xsd">
  <passages>
    <passage indexedname="příjezdová cesta-bazén1" from="příjezdová cesta u wagnerů" to="u wagnerova bazénu" door="false" closed="false" coordinates="1001, 1040, 1010, 1040" />
    <passage indexedname="bazén-hala1" from="u wagnerova bazénu" to="hala u wagnerů" door="true" closed="true" coordinates="1039, 1052, 1039, 1048" />
  </passages>
  <localities>
    <locality indexedname="příjezdová cesta u wagnerů" friendlyname="příjezdová cesta" coordinates="1000, 1040, 1040, 1000" type="Outdoor" defaultTerrain="Asfalt" walls="None" height="0">
      <panel terrain="Tiles" coordinates="0, 0, 24, 4" canBeOccupied="true" />
      <panel terrain="Bush" coordinates="11, 0, 39, 0" canBeOccupied="false" />
      <panel terrain="Gravel" coordinates="0, 5, 24, 40" canBeOccupied="true" />
      <panel terrain="Gravel" coordinates="35, 1, 40, 40" canBeOccupied="true" />
      <object indexedname="plot na příjezdové cestě" type="none" friendlyname="plot" coordinates="0, 0, 0, 5" />
      <object indexedname="columbovo auto" type="columbovo auto" friendlyname="tvoje auto" coordinates="25, 30, 27, 34" />
      <object indexedname="brána u wagnerů" type="none" friendlyname="brána" coordinates="23, 40, 39, 40" />
      <object indexedname="plot u wagnerů2" type="none" friendlyname="plot" coordinates="0, 6, 21, 6" />
      <object indexedname="plot u wagnerů3" type="none" friendlyname="plot" coordinates="22, 6, 22, 40" />
      <object indexedname="plot u wagnerů4" type="none" friendlyname="plot" coordinates="40, 0, 40, 40" />
    </locality>
    <locality indexedname="u wagnerova bazénu" friendlyname="u bazénu" coordinates="900, 1100, 1039, 1041" type="Outdoor" height="0" walls="Left, Front, Right" defaultTerrain="Tiles">
      <panel terrain="Tiles" coordinates="139, 48, 139, 52" canBeOccupied="true" />
      <panel terrain="Clay" coordinates="1, 1, 20, 58" canBeOccupied="true" />
      <panel terrain="Clay" coordinates="21, 1, 138, 9" canBeOccupied="true" />
      <panel terrain="Grass" coordinates="23, 2, 131, 7" canBeOccupied="true" />
      <panel terrain="Bush" coordinates="30, 1, 42, 2" canBeOccupied="true" />
      <panel terrain="Bush" coordinates="18, 1, 25, 2" canBeOccupied="true" />
      <panel terrain="Bush" coordinates="8, 1, 13, 2" canBeOccupied="true" />
      <panel terrain="Bush" coordinates="2, 1, 4, 2" canBeOccupied="true" />
      <panel terrain="Grass" coordinates="3, 4, 18, 12" canBeOccupied="true" />
      <panel terrain="Grass" coordinates="2, 30, 18, 57" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="31, 34, 33, 40" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="34, 33, 38, 38" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="36, 31, 39, 32" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="35, 32, 35, 32" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="37, 30, 39, 30" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="37, 30, 39, 30" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="38, 29, 39, 29" canBeOccupied="true" />
      <panel terrain="Puddle" coordinates="39, 28, 39, 28" canBeOccupied="true" />
      <panel terrain="Concrete" coordinates="12, 32, 18, 38" canBeOccupied="true" />
      <object indexedname="strom u bazénu1" type="none" friendlyname="strom" coordinates="4, 5, 4, 5" />
      <object indexedname="strom u bazénu2" type="none" friendlyname="strom" coordinates="2, 34, 2, 34" />
      <object indexedname="strom u bazénu3" type="none" friendlyname="strom" coordinates="2, 44, 2, 44" />
      <object indexedname="strom u bazénu4" type="none" friendlyname="strom" coordinates="2, 57, 2, 57" />
      <object indexedname="wagnerova mrtvola" type="none" friendlyname="mrtvola" coordinates="36, 39, 36, 40" />
      <object indexedname="záhon růží u bazénu" type="none" friendlyname="růže" coordinates="2, 18, 12, 24" />
      <object indexedname="gril u bazénu" type="none" friendlyname="gril" coordinates="13, 35, 15, 35" />
      <object indexedname="lavička u bazénu1" type="none" friendlyname="lavička" coordinates="12, 39, 17, 40" />
      <object indexedname="lavička u bazénu2" type="none" friendlyname="lavička" coordinates="12, 30, 15, 31" />
      <object indexedname="lavička u bazénu3" type="none" friendlyname="lavička" coordinates="10, 31, 11, 40" />
      <object indexedname="zahradní hadice u bazénu" type="none" friendlyname="hadice" coordinates="1, 37, 1, 39" />
      <object indexedname="telefon u bazénu" type="none" friendlyname="telefon" coordinates="81, 30, 81, 30" />
      <object indexedname="popelnice u bazénu" type="none" friendlyname="popelnice" coordinates="12, 58, 12, 58" />
      <object indexedname="odrazové prkno u bazénu" type="none" friendlyname="prkno" coordinates="39, 36, 39, 36" />
      <object indexedname="schůdky u bazénu" type="none" friendlyname="schůdky" coordinates="39, 38, 39, 39" />
      <object indexedname="bazén u wagnerů" type="none" friendlyname="bazén" coordinates="40, 20, 80, 40" />
      <object indexedname="plot u wagnerů5" type="none" friendlyname="plot" coordinates="1, 59, 100, 59" />
    </locality>
    <locality indexedname="hala u wagnerů" friendlyname="hala" type="Indoor" defaultTerrain="Carpet" height="4" walls="Front, Right, Back" coordinates="1040, 1059, 1058, 1041">
      <object indexedname="okno v hale1" type="none" friendlyname="okno" coordinates="11, 18, 17, 18" />
      <object indexedname="vitrýna v hale" type="none" friendlyname="vitrýna" coordinates="3, 17, 10, 17" />
      <object indexedname="dveře v hale" type="none" friendlyname="dveře" coordinates="6, 0, 6, 0" />
      <object indexedname="rádio v hale" type="none" friendlyname="rádio" coordinates="0, 1, 0, 1" />
      <object indexedname="pracovní stůl v hale" type="none" friendlyname="stůl" coordinates="1, 1, 2, 2" />
      <object indexedname="židle u pracovního stolu v hale" type="none" friendlyname="židle" coordinates="1, 3, 1, 3" />
      <object indexedname="telefon v hale" type="none" friendlyname="telefon" coordinates="3, 1, 3, 1" />
      <object indexedname="barový pult v hale" type="none" friendlyname="barový pult" coordinates="10, 3, 10, 12" />
      <object indexedname="barová stolička v hale1" type="none" friendlyname="barová stolička" coordinates="9, 4, 9, 4" />
      <object indexedname="barová stolička v hale2" type="none" friendlyname="barová stolička" coordinates="9, 6, 9, 6" />
      <object indexedname="barová stolička v hale3" type="none" friendlyname="barová stolička" coordinates="9, 8, 9, 8" />
      <object indexedname="barová stolička v hale4" type="none" friendlyname="barová stolička" coordinates="9, 10, 9, 10" />
      <object indexedname="barová stolička v hale5" type="none" friendlyname="barová stolička" coordinates="9, 12, 9, 12" />
      <object indexedname="lednice v hale" type="none" friendlyname="lednice s minibarem" coordinates="16, 2, 17, 5" />
      <object indexedname="kávovar v hale" type="none" friendlyname="kávovar" coordinates="17, 6, 17, 6" />
      <object indexedname="dřes v hale" type="none" friendlyname="dřes" coordinates="17, 7, 17, 7" />
      <object indexedname="police s nádobím v hale" type="none" friendlyname="police s nádobím" coordinates="17, 8, 17, 10" />
    </locality>
    <locality indexedname="parkoviště u stadionu" friendlyname="parkoviště" type="Outdoor" defaultTerrain="Concrete" height="0" walls="None" coordinates="1059, 1180, 1130, 1058">
      <panel terrain="Wall" coordinates="71, 0, 71, 10" canBeOccupied="false" />
      <panel terrain="Wall" coordinates="0, 0, 0, 10" canBeOccupied="false" />
      <object indexedname="dálnice u stadionu" type="none" friendlyname="dálnice" coordinates="0, 103, 71, 122" />
      <object indexedname="živý plot u stadionu1" type="none" friendlyname="živý plot" coordinates="71, 11, 71, 102" />
      <object indexedname="živý plot u stadionu2" type="none" friendlyname="živý plot" coordinates="0, 10, 0, 102" />
      <object indexedname="auto u stadionu1" type="none" friendlyname="auto" coordinates="9, 82, 12, 87" />
      <object indexedname="auto u stadionu2" type="none" friendlyname="auto" coordinates="15, 81, 18, 86" />
      <object indexedname="auto u stadionu3" type="none" friendlyname="auto" coordinates="21, 79, 24, 84" />
      <object indexedname="auto u stadionu4" type="none" friendlyname="auto" coordinates="28, 82, 31, 88" />
      <object indexedname="auto u stadionu5" type="none" friendlyname="auto" coordinates="35, 82, 39, 87" />
      <object indexedname="auto u stadionu6" type="none" friendlyname="auto" coordinates="45, 79, 49, 84" />
      <object indexedname="auto u stadionu7" type="none" friendlyname="auto" coordinates="51, 76, 55, 82" />
      <object indexedname="auto u stadionu8" type="none" friendlyname="auto" coordinates="59, 77, 63, 82" />
      <object indexedname="auto u stadionu9" type="none" friendlyname="auto" coordinates="66, 76, 70, 82" />
    </locality>
  </localities>
</map>
